main = ".open-next/worker.js"
name = "wesbos"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# The binding name must be "ASSETS" when the cache is enabled
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[ d1_databases ]]
binding = "DB"
database_name = "wes-bos-social-cache"
database_id = "44adcb8f-8ad1-408b-8da1-8dca56a879b2"
migrations_dir = "migrations"